name: Freeze Check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  freeze-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sanity
        run: |
          echo "Repo fenced via PR-only. Nothing to do."
          test -f README.md || echo "README missing (non-blocking)."
