name: Freeze Check
on:
  pull_request: { branches: [ main ] }
permissions: { contents: read, pull-requests: read }
jobs:
  freeze-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: List changed files
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          git diff --name-only origin/${{ github.base_ref }}... > changed.txt
          echo "Changed files:" && cat changed.txt
      - name: Fail if frozen page files changed
        run: |
          printf "%s\n" \
            "client/src/pages/home.tsx" \
            "client/src/pages/products.tsx" \
            "client/src/pages/cart.tsx" \
            "client/src/pages/ffl-selection.tsx" \
            "client/src/pages/shipping.tsx" \
            "client/src/pages/billing.tsx" \
            "client/src/pages/payment.tsx" \
            "client/src/pages/order-confirmation.tsx" \
            "client/src/pages/account.tsx" \
            > frozen_pages.txt
          if grep -Fxf frozen_pages.txt changed.txt >/dev/null 2>&1; then
            echo "❌ Frozen customer UI files were modified:"
            grep -Fxf frozen_pages.txt changed.txt || true
            exit 1
          fi
          echo "✅ No frozen page file changes."
      - name: If server/routes.ts changed, ensure frozen APIs untouched
        run: |
          if ! grep -Fxq "server/routes.ts" changed.txt; then
            echo "server/routes.ts not changed."; exit 0; fi
          git diff -U0 origin/${{ github.base_ref }}... -- server/routes.ts > routes.diff
          test -f FREEZE-PUBLIC.txt || { echo "FREEZE-PUBLIC.txt missing"; exit 1; }
          if grep '^+' routes.diff | grep -Ff FREEZE-PUBLIC.txt >/dev/null 2>&1; then
            echo "❌ Diff touches frozen public API routes from FREEZE-PUBLIC.txt"
            grep '^+' routes.diff | grep -Ff FREEZE-PUBLIC.txt || true
            exit 1
          fi
          echo "✅ Frozen public API routes were not modified."
